### ISSUE TITLE
ERROR: unmatched right bracket

### ISSUE THREAD

**Issue by IgorBuchelnikov** [Tvangeste/dsl2mobi#1]
Error while executing command:

C:\Users\Igor>ruby C:\Ruby187\Scripts\Dsl2Mobi\dsl2mobi.rb -i C:\Ruby187\LingvoUniversalEnRu_new.dsl -o C:\Ruby187\LingvoUniversalEnRu

ERROR: unmatched right bracket at pos 16, state text, string 1) [p][i][c]яЁюёЄ.[
/i][/p]; = [ref]Harry[/ref][/c]

You can download LingvoUniversalEnRu_new.dsl from http://www.onlinedisk.ru/file/802323/
File will be avalible till  2012-03-09

**Comment by Tvangeste** [comment]
In some rare cases the tags normalization in the script couldn't handle the weird tag order in the original DSL file. The easiest way to fix this is to manually adjust those cases, moving tags around.
